# Generated by Django 5.0.4 on 2024-04-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mti', models.CharField(max_length=4, null=True)),
                ('processingCode', models.CharField(max_length=6, null=True)),
                ('transactionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateTimeTransaction', models.DateTimeField()),
                ('cardholderBillingConversionRate', models.CharField(max_length=8, null=True)),
                ('stan', models.CharField(max_length=10, null=True)),
                ('timeLocalTransaction', models.CharField(max_length=6, null=True)),
                ('dateLocalTransaction', models.CharField(max_length=4, null=True)),
                ('expiryDate', models.CharField(max_length=4, null=True)),
                ('conversionDate', models.CharField(max_length=4, null=True)),
                ('merchantCategoryCode', models.CharField(max_length=4, null=True)),
                ('posEntryMode', models.CharField(max_length=3, null=True)),
                ('acquiringInstitutionCode', models.CharField(max_length=6, null=True)),
                ('forwardingInstitutionCode', models.CharField(max_length=6, null=True)),
                ('rrn', models.CharField(max_length=10, null=True)),
                ('cardAcceptorTerminalId', models.CharField(max_length=10)),
                ('cardAcceptorId', models.CharField(max_length=9)),
                ('cardAcceptorNameLocation', models.CharField(max_length=50)),
                ('cardBalance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additionalData48', models.CharField(max_length=1, null=True)),
                ('transactionCurrencyCode', models.CharField(max_length=3)),
                ('cardholderBillingCurrencyCode', models.CharField(max_length=3, null=True)),
                ('posDataCode', models.CharField(max_length=24)),
                ('originalDataElement', models.CharField(max_length=36, null=True)),
                ('channel', models.CharField(max_length=4)),
                ('encryptedPan', models.CharField(max_length=44, null=True)),
                ('network', models.CharField(max_length=10, null=True)),
                ('dcc', models.BooleanField(null=True)),
                ('kitNo', models.CharField(max_length=10, null=True)),
                ('factorOfAuthorization', models.IntegerField(null=True)),
                ('authenticationScore', models.IntegerField(null=True)),
                ('contactless', models.BooleanField(null=True)),
                ('international', models.BooleanField()),
                ('preValidated', models.BooleanField()),
                ('enhancedLimitWhiteListing', models.BooleanField(null=True)),
                ('transactionOrigin', models.CharField(max_length=4, null=True)),
                ('transactionType', models.CharField(max_length=4, null=True)),
                ('isExternalAuth', models.BooleanField(null=True)),
                ('encryptedHexCardNo', models.CharField(max_length=64, null=True)),
                ('isTokenized', models.BooleanField(null=True)),
                ('entityId', models.CharField(max_length=10, null=True)),
                ('moneySendTxn', models.BooleanField(null=True)),
                ('mcRefundTxn', models.BooleanField(null=True)),
                ('mpqrtxn', models.BooleanField(null=True)),
                ('authorisationStatus', models.BooleanField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
